"""add_rating_statistics_table

Revision ID: 6c41231d8f22
Revises: fff6ecfd11d2
Create Date: 2025-03-14 17:55:19.366049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c41231d8f22'
down_revision = 'fff6ecfd11d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('rating_type', sa.String(), nullable=True),
    sa.Column('rating_value', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_statistics_id'), 'rating_statistics', ['id'], unique=False)
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_restaurants_email', table_name='restaurants')
    op.drop_column('restaurants', 'logo')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'email')
    op.drop_column('restaurants', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_restaurants_email', 'restaurants', ['email'], unique=False)
    op.alter_column('restaurants', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('restaurants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rating_statistics_id'), table_name='rating_statistics')
    op.drop_table('rating_statistics')
    # ### end Alembic commands ### 