"""add_star_click_statistics_table

Revision ID: 788ce76b7613
Revises: 6c41231d8f22
Create Date: 2025-03-14 18:03:28.327303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788ce76b7613'
down_revision = '6c41231d8f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 