"""add_subdomain_to_restaurant

Revision ID: fff6ecfd11d2
Revises: 
Create Date: 2025-03-13 00:45:30.132684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fff6ecfd11d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('email', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('address', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('logo', sa.String(), nullable=True))
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_restaurants_email'), 'restaurants', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_email'), table_name='restaurants')
    op.alter_column('restaurants', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('restaurants', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('restaurants', 'logo')
    op.drop_column('restaurants', 'address')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'email')
    # ### end Alembic commands ### 